### PR TITLE
D3 visualisations

### PR DESCRIPTION
**Pull request by aswanipranjal**
PR for issue #4.
Added

1. requirements.txt
2. visualisations.py
3. Visualisations/top_edges.html

On running `python visualisations.py`, `top_edges_graph.json` file will be created which will be saved in the `Visualisations` folder.
D3.js graph can be viewed at `localhost:8000/Visualisations/top_edges.html` in your browser.

Double clicking the node will highlight it and it's child nodes.
Magnitude between the nodes is displayed by changing the color and the opacity of the links in between.

### CODE REVIEW

**Comment by yochannah** [comment]
Hey @aswanipranjal! This is looking like a great start! A couple of notes:

- I think there's some bug with the layout or a number somewhere. When I load the top edges html in my browser shows this every tick:
image
- Am I right in thinking this is python 2.7 only (that's fine, I'm just making sure).

**Comment by aswanipranjal** [comment]
Hi @yochannah! Yes, I am using python 2.7.10 for this.
It looks like the code is trying to create a node from number 0. Can you please show me the `top_edges_graph.json` file that was generated in the `Visualizations` folder,  when you ran `python visualizations.py`?
Also, is *anything* showing up when you load the html page?

**Comment by yochannah** [comment]
@aswanipranjal Here's the json file: https://github.com/yochannah/similarity/blob/edges-graph-bug/Visualisations/top_edges_graph.json 

and this is what the screen looks like - it seems to be drawing the elements but not positioning them correctly (I shrunk the svg height to make the screenshot smaller): 
image

**Comment by aswanipranjal** [comment]
@yochannah I think it is a networkx version issue because the file that is generated has `source` and `target` values for the nodes as their respective index values as seen in the links object.
I am using networkx version 2.0. Can you please tell me what version are you using?

I've pushed to [my fork](https://github.com/aswanipranjal/similarity/tree/master) and I've added the [graph file](https://github.com/aswanipranjal/similarity/blob/master/Visualisations/top_edges_graph.json) that gets generated in my system, for reference.

**Comment by yochannah** [comment]
You were right!

**Comment by yochannah** [comment]
Looking brilliant! We'll probably add some follow-on tasks later this week - you're welcome to pick them up if you're interested or leave it for someone else. 

If you'd like me to send an InterMine sticker your way, email me your preferred mailing address to yo@intermine.org:)

**Comment by yochannah** [comment]
image

**Comment by aswanipranjal** [comment]
Thank you @yochannah! I'd be happy to take on more tasks. I am also looking into the rest of the results present in the repo to make visualisations for them.

**Pull request merged**
