### PR TITLE
Added functionality to fetch data via webservice and show on page.

### LINKED ISSUE #6: On click, fetch data via webservice and display on page
Thanks to @aswanipranjal we now have a D3 visualisation of our top edges file: https://github.com/intermine/similarity/issues/4 (Demo: [https://yochannah.github.io/similarity/Visualisations/top_edges.html](https://yochannah.github.io/similarity/Visualisations/top_edges.html))

## Background: 

Each node is denoted by identifiers which denote fly genes. For example, the fly gene `FBgn0001325` has a report page on FlyMine: http://www.flymine.org/flymine/portal.do?externalids=FBgn0001325&class=Gene - it is also possible to fetch this data from FlyMine via a webservice. An example minimal data fetch using the im.js library is available here: http://jsbin.com/nuvazuh/edit?html,console

## Task:
Currently, we have a nice tooltip that shows the name of the gene (node) you're hovering over. Expand functionality so that on-click we populate an information box with the following fields, fetched from the web-services:

- [ ] primary identifier
- [ ] secondary identifier
- [ ] organism name
- [ ] gene symbol

- [ ] [optional] Bonus points if this is touchscreen-friendly!

im.js docs: http://alexkalderimis.github.io/imjs/
interactive API docs: http://iodocs.apps.intermine.org/

You may also be interested in #7 

### Right, I'm in! How do I get started?

1. Fork this repo and make sure you can view the visualisation in question. This PR #5 has useful troubleshooting info if needed.  
2. Comment on the task and tell us you want to come play! Share any mocks you may have made.
3. Get coding! We can advise you on queries relating to InterMine and the similarity project results if you have questions.
4. Once you're ready to make a PR, do so. Remember that small, granular commits are better than big "all in one go" commits and PRs.

### If you need help

Comment on this issue and mention @joshkh, @yochannah, or check out other ways to contact us, e.g. chat, email: http://intermine.readthedocs.io/en/latest/about/contact-us/

### PR DESCRIPTION
**Pull request by aswanipranjal**
Closes #6 
On clicking any node, It fetches the
- primaryIdentifier
- secondaryIdentifier
- organism name
- gene symbol and displays it on the page.
- It is touch screen friendly (tested on my mobile device). 

 It also tags the node with it's `primaryIdentifier`.

### CODE REVIEW

**Comment by yochannah** [comment]
@aswanipranjal Sorry for the delay reviewing this! I've been off sick with the flu :( I will get to it this week.

**Comment by aswanipranjal** [comment]
@yochannah, it's not a problem. Get well soon!

**Comment by yochannah** [comment]
@aswanipranjal Looking Great! Thanks!

P.S. - Your stickers are in the post, let us know when they arrive! :)

**Comment by aswanipranjal** [comment]
Sure :bowtie:

**Comment by aswanipranjal** [comment]
Hey @yochannah the stickers finally arrived and they are **AWESOME**!! Thankyou so much!
img_20180213_223544929
This will motivate me to contribute more to open source. I am also applying for GSoC-18 under Intermine. Hope to work with you soon!
Thanks again!

**Comment by yochannah** [comment]
Awesome to see the stickers in place! :heart_eyes: And we'll look forward to your application - don't hesitate to email us or drop by chat if you need to ask any questions.

**Pull request merged**
