### PR TITLE
Firsttimers issue #10

### PR DESCRIPTION
**Pull request by akashp-git**
Pull request for the issue 'Add title to interactive content [mostly html changes, perhaps some js] (#10)'
Branch firsttimers-issue-#10 contains the changes done.

### CODE REVIEW

**Comment by yochannah** [comment]
@amand1996 If you get time, if would be great if you could review this PR. Thanks!

**Comment by amand1996** [comment]
It looks good. Though I have some points in my mind. The code inserts an extra row to the table generated by `imtables.js` library for the purpose of table heading (while I think it would have been better not to manipulate the table generated by the library, rather one should insert a heading on top of the table div). Also, if the above is followed, I don't think there will be any need of `setTimeOut`.
(`setTimeOut` certainly does the work, but use of such looping mechanism is not a good practice)

**Comment by akashp-git** [comment]
Hi @amand1996 thanks for reviewing the code. I'll try to make the changes and submit a new PR.

**Comment by akashp-git** [comment]
Hi @amand1996 , there are two div elements with same id "left_div", the second div contains the table. So how should i proceed, should i change the id of any one of the div or access the element by its index after getting all the div elements by tag name ??

**Comment by yochannah** [comment]
Renaming the div should be fine!

**Comment by akashp-git** [comment]
PFA of the screenshot.

The first "left_div" contains the graph and the next "left_div" contains the table, please let  me know which div to change and any relevant name for it.

capture

**Comment by yochannah** [comment]
Use your judgement - we don't mind what they're named so long as they make sense! maybe "graph" and "table", or something like that?

**Review by amand1996 — APPROVED** [review]
Looks Good. :) 👍

**Comment by akashp-git** [comment]
Hi @yochannah , @amand1996 thanks for merging the pull requests

**Comment by yochannah** [comment]
@a99web sorry for it taking so long! I came to look on the repo for some other reason and thought "oh no, I'm so sorry I forgot you!" :) thanks for your help and patience!!

**Pull request merged**
