### PR TITLE
updated top_edges.css for cursor pointer 

### PR DESCRIPTION
**Pull request by nowchris**
Issue #11: Updated the classes defined in top_edges css to match the classes called in the html. Added a pointer style to the nodes class.

### CODE REVIEW

**Comment by yochannah** [comment]
Fixes #11 

@nowchris Thanks for the PR, it looks good! 

One small thing (and don't worry about it this time, we can remove it and add ds store to the .gitignore file so it doesn't happen again) - try not to check in system files like `.DS_store` where possible. No biggie though - we're grateful for your contribution! :)

Was this your first Open Source PR, btw? If so, congrats and well done! :tada:

**Comment by yochannah** [comment]
@nowchris by the way, was everything straightforward for you? Any feedback or anything we could have made easier?

If you'd like an InterMine sticker sent through the post by way of thanks, email me your physical mailing address to yo@intermine.org and I'll send one out.

**Comment by nowchris** [comment]
@yochannah Thanks for merging my request! Good to know RE: the DS_Store file, I'll take that tip to my future PRs! But, yup, this was my first Open Source PR! It was recommended to me to take a look at the [first timers twitter](https://twitter.com/first_tmrs_only). That's where I came across this issue that I knew I could solve. 

The task was totally straight forward! Though, I just had to watch a YouTube tutorial to ensure that I was making the request correctly. Maybe providing one that you know is good would help other first timers. I believe I watched [this one](https://www.youtube.com/watch?v=YTbRzhQju4c), but I also used GitHub desktop with Atom editor so it was a little different.

**Comment by yochannah** [comment]
@nowchris The video recommendation is a really great idea - I'll take that on board! Thanks!! :)

**Pull request merged**
